name: Container Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Release - ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - api-gateway
          - order-service
          - payment-service

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:sha-${{ github.sha }} \
            ./${{ matrix.service }}

      - name: Scan container image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:sha-${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: "1"

      - name: Push container image
        run: |
          docker push \
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:sha-${{ github.sha }}
